[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables needed for the app:
# VITE_OPENAI_KEY - Your OpenAI API key
# VITE_DEMO_KEY - Secret demo key (users enter this to use VITE_OPENAI_KEY)
# VITE_DEMO_USER - Demo user email (gets automatic access to VITE_OPENAI_KEY)
# VITE_GOOGLE_CLIENT_ID - Your Google OAuth client ID
