[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/organizations"
  to = "/.netlify/functions/organizations"
  status = 200

[[redirects]]
  from = "/api/organizations/:organizationId/checks"
  to = "/.netlify/functions/organization-checks/:organizationId/checks"
  status = 200

[[redirects]]
  from = "/api/checks/:checkId/results"
  to = "/.netlify/functions/check-results/:checkId"
  status = 200

# Frontend redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS redirects
[[redirects]]
  from = "http://getzenith.ai/*"
  to = "https://getzenith.ai/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.getzenith.ai/*"
  to = "https://getzenith.ai/:splat"
  status = 301
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Environment variables needed for the app:
# VITE_OPENAI_KEY - Your OpenAI API key
# VITE_DEMO_KEY - Secret demo key (users enter this to use VITE_OPENAI_KEY)
# VITE_DEMO_USER - Demo user email (gets automatic access to VITE_OPENAI_KEY)
# VITE_GOOGLE_CLIENT_ID - Your Google OAuth client ID
# VITE_BACKEND_URL - Backend API URL (e.g., https://your-backend-domain.com)
